name: x86_64 immortalwrt

on:
  # repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  ImmortalWrt-21_02:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E swapoff -a
        sudo -E rm -f /swapfile
        sudo -E docker image prune -a -f
        sudo -E snap set system refresh.retain=2
        sudo -E apt -y purge azure-cli dotnet* firefox ghc* google* llvm* mono* mysql* openjdk* php* zulu* powershell* msodbc* android*
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E rm -rf /usr/share/dotnet /usr/local/lib/android/sdk /etc/mysql /etc/php
        sudo -E apt update -y
        sudo -E apt install -y libfuse-dev
        sudo -E bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
    - name: Clone Source
      run: |
        cd "/home/runner"
        git clone -b openwrt-21.02 --single-branch https://github.com/immortalwrt/immortalwrt
        sudo chown -R runner:runner "immortalwrt"
        cd "/home/runner/immortalwrt"
        sed -i '$a src-git-full kenzo https://github.com/kenzok8/openwrt-packages;master' feeds.conf.default
        sed -i '$a src-git-full small https://github.com/kenzok8/small;master' feeds.conf.default
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        svn export https://github.com/sbwml/packages_lang_golang/branches/19.x feeds/packages/lang/golang
        ./scripts/feeds install -a
    - name: Build ImmortalWrt-21.02
      id: firmware
      run: |
        cd "/home/runner/immortalwrt"
        cp -f "${GITHUB_WORKSPACE}/diffconfig_x86_64_immortalwrt" ".config"
        make defconfig
        make -j$[$(nproc)+1]
        echo "firmware_status=success" >> $GITHUB_OUTPUT
    - name: Get Info
      id: info
      run: echo "release_date=$(date +"%Y.%m.%d")" >> $GITHUB_OUTPUT
    - name: Release
      uses: softprops/action-gh-release@v1
      if: steps.firmware.outputs.firmware_status == 'success' && !cancelled()
      with:
        name: ${{ steps.info.outputs.release_date }} x86-64 ImmortalWrt
        tag_name: ${{ steps.info.outputs.release_date }}-ImmortalWrt
        files: /home/runner/immortalwrt/bin/targets/x86/64/*
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 3
        keep_minimum_runs: 2
    - name: Delete old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
